# Версия формата docker-compose
#version: "3.9"

# Определение сервисов
services:

  # Сервис PostgreSQL
  postgres:
    image: postgres:17-alpine  # Использование образа PostgreSQL версии 17 на базе Alpine Linux
    environment:
      POSTGRES_USER: root  # Имя пользователя для PostgreSQL
      POSTGRES_PASSWORD: secret  # Пароль для PostgreSQL
      POSTGRES_DB: simplebank  # Название базы данных

  # Сервис API
  api:
    build:
      context: .  # Контекст сборки (текущая директория)
      dockerfile: Dockerfile  # Использование Dockerfile для сборки образа
    ports:
      - "8080:8080"  # Проброс порта 8080 контейнера на порт 8080 хоста
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simplebank?sslmode=disable  # Переменная окружения для подключения к PostgreSQL
    depends_on:
      - postgres  # Указывает, что сервис api зависит от сервиса postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]  # Точка входа для запуска скрипта
    command: ["/app/main"]  # Команда для запуска приложения