# Версия формата docker-compose
#version: "3.9"

# Определение сервисов
services:

  # Сервис PostgreSQL
  postgres:
    image: postgres:17-alpine  # Использование образа PostgreSQL версии 17 на базе Alpine Linux
    environment:
      POSTGRES_USER: root  # Имя пользователя для PostgreSQL
      POSTGRES_PASSWORD: secret  # Пароль для PostgreSQL
      POSTGRES_DB: simplebank  # Название базы данных
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.4.2-alpine

  # Сервис API
  api:
    build:
      context: .  # Контекст сборки (текущая директория)
      dockerfile: Dockerfile  # Использование Dockerfile для сборки образа
    ports:
      - "8080:8080"  # Проброс порта 8080 контейнера на порт 8080 хоста
      - "9090:9090"  # Проброс порта 9090 контейнера на порт 9090 хоста
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simplebank?sslmode=disable # Переменная окружения для подключения к PostgreSQL
      - REDIS_SERVER_ADDRESS=redis:6379 # Переменная окружения для подключения к Redis
    depends_on:
      - postgres  # Указывает, что сервис api зависит от сервиса postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]  # Точка входа для запуска скрипта
    command: ["/app/main"]  # Команда для запуска приложения
volumes:
  db-data: